name: commons-wordpress
recipe: lemp
services:
  appserver:
    type: php:custom
    overrides:
      build: .
      image: knowledge-commons/wordpress:8.1
      environment:
        XDEBUG_MODE:
        XDEBUG_CONFIG:
    build_as_root:
      - rm -f site/.env && ln -s /app/config/local/wordpress/.env site/.env
      - rm -f site/web/phpinfo.php && ln -s /app/config/local/php/phpinfo.php site/web/phpinfo.php
      - /app/.lando/build-wordpress.sh
      - cd /app/core-plugins/humcore/ && composer update
    config:
      php: config/local/php/php.ini
  appserver_nginx:
    scanner:
      okCodes:
        - 500
  database:
    type: mariadb
    portforward: 3306
    creds:
      user: wordpress
      password: wordpress
      database: wordpress
    volume:
      - database:/var/lib/mysql
env_file:
  - .lando/secrets-default.env
  - .lando/secrets.env
config:
  config:
    vhosts: config/local/nginx/nginx.conf
tooling:
  wp:
    service: appserver
    description: Runs WP-CLI commands
    cmd: wp
  aws:
    service: appserver
    description: Runs AWS CLI commands
    cmd: aws
  get-local-secrets:
    service: appserver
    description: Gets local secrets from AWS Secrets Manager
    cmd: /app/scripts/get-local-secrets.php
  s3-pull:
    service: appserver
    description: Pulls content from S3
    cmd: /app/scripts/s3-pull.php
  