services:
  appserver:
    overrides:
      volumes:
        - type: volume
          source: wp_uploads
          target: /media
          read_only: true
          volume:
            nocopy: true
        - type: volume
          source: wp_content
          target: /content
          read_only: false
    build_as_root:
      - adduser www-data xfs
    run_as_root:
      - |
        ln -sf /media/uploads /app/site/web/app/uploads && \
        ln -sf /media/blogs.dir /app/site/web/app/blogs.dir && \
        ln -sf /content/plugins/* /app/site/web/wp-content/plugins/ && \
        ln -sf /content/themes/* /app/site/web/wp-content/themes/
  cron:
    services:
      volumes:
        - type: volume
          source: wp_uploads
          target: /media
          read_only: true
          volume:
            nocopy: true
        - type: volume
          source: wp_content
          target: /content
          read_only: false
    volumes:
      wp_uploads:
        driver: local
        driver_opts:
          type: nfs
          o: addr=10.98.11.28,ro,nfsvers=4
          device: ":/"
      wp_content:
        driver: local
        driver_opts:
          type: nfs
          o: addr=10.98.11.233,rw,nfsvers=4
          device: ":/"
  appserver_nginx:
    overrides:
      volumes:
        - type: volume
          source: wp_uploads
          target: /media
          read_only: true
          volume:
            nocopy: true
        - type: volume
          source: wp_content
          target: /content
          read_only: false
    build_as_root:
      - adduser daemon www-data
