services:
  appserver:
    overrides:
      volumes:
        - type: volume
          source: wp_uploads
          target: /media
          volume:
            nocopy: true
    build_as_root:
      - adduser www-data xfs
    run_as_root:
      - |
        mkdir -p /media && \
        chown www-data:www-data /media && \
        rm -rf /app/site/web/app/uploads && \
        ln -s /media/uploads /app/site/web/app/uploads && \
        rm -rf /app/site/web/app/blogs.dir && \
        ln -s /media/blogs.dir /app/site/web/app/blogs.dir
  cron:
    services:
      volumes:
        - wp_uploads:/media
    volumes:
      wp_uploads:
        driver: local
        driver_opts:
          type: nfs
          o: addr=10.100.11.189,ro,nfsvers=4
          device: ":/"
  appserver_nginx:
    overrides:
      volumes:
        - type: volume
          source: wp_uploads
          target: /media
          volume:
            nocopy: true
    build_as_root:
      - adduser daemon www-data
      - adduser daemon dialout
