# Nginx container for running WordPress on production

FROM nginx:stable-alpine

RUN adduser nginx www-data

COPY ./config/all/nginx/nginx.conf /etc/nginx/
COPY ./config/all/nginx/templates /etc/nginx/templates