<?php
echo "****************insert_academic_interests****************\n";
$set_term = wp_insert_term( '2666', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Academe', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Academic novels', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Adam Smith', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Adam Smith and literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Adam Smith and philosophy', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Adorno', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Aesthetics', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'African American culture', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'African American literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'African history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'African languages', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'African literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Ambrose Bierce', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'American history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'American literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Animal studies', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Arabic language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Arab world', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Argentina', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Armenian language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Armenian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Art history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Asian history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Autobiography', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Biblical studies', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Biography', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Blogs', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Boys\' love', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'British literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Canadian history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Canadian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Cardinal John Henry Newman', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Caribbean literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Catalan literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Cervantes', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Charles Kingsley', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Chicana literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Children\'s literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Chinese language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Chinese literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Circus', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Citizenship', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Classical literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Cognitive science', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Cold war', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Collaboration', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Colonial Latin American literature and culture', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Comedia', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Commedia dell\'arte', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Comparative literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Comparative religion', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Compilation', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Composition', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Concealment', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Confession', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Contemporary fiction', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Contemporary literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Contracts', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Cosmopolitanism', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Criticism', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Cuban novel', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Cultural displacement', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Cultural studies', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Culture studies', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Darwin', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'David Mitchell', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Decolonial theory', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Desire', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Digital humanities', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Digital reading', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Donato Ndongo', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Don Delillo', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Drag', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Drama', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'E-readers', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'E-reading', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Early modern studies', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Ecocriticism', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Economics', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Education', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Ekphrasis', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Eliot', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Emerson', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Empathy', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Encyclopedias', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'English language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'English literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Enlightenment', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Entremeses', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Epistemology', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Ethics', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'European history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'European integration', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'European literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'European Union', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Fandom', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Fanon', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Feminist philosophy', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Fiction', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Film', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Film studies', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Formalism', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Francis Hutcheson', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Francophone literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'French Canadian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'French Creole', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'French language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'French literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Geography', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Germanic literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'German language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Global nomads', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Global south', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Greek language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Greek literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Gujarati language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hardware', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hebrew language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hebrew literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hermeneutics', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hindi language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'History', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'History and literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hitchcock', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hmong language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hmong literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hobbes', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Humanism', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Human rights', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hungarian language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Hungarian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Icelandic literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Illustrated books', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'India', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Indian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'individuality', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Inke', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Intellectual history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Iraq war', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Irish literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Italian language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Italian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'J.M. Coetzee', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Japanese-American', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Japanese language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Japanese literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Jennifer Egan', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Jose Saramago', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Junot Diaz', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Karen Joy Fowler', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Knowledge environments', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Korean language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Korean literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Lacan', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Laotian language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Laotian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Latin American history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Latin American literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Law', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Law and literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Lebanon', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Linguistics', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Literary geography', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Literary history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Literary theory', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Literature and economics', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Literature and medicine', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Literature and philosophy', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Literature and psychology', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Literature and science', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Lope de Vega', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Ludwig Wittgenstein', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Macguffin', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Machine learning', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Malaysian digital independent film', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Marginalized sexualities', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Marilynne Robinson', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Media history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Media studies', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Medieval history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Medieval literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Memory studies', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Metaphysics', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Methodology', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Michel Foucault', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Microhistory', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Middle Eastern history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Middle Eastern languages', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Middle Eastern literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Migrant literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Migration', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Modern history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Modernism', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Modern language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Modern literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Mon-Khmer languages', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Mystory', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Nabokov', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Narrative theory', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'National identity', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Native American languages', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Native American literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Neh', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Neo-Victorian', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Open access', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Oxford Movement', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Paris', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Passing', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Pedagogy', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Periodicals', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Persian language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Persian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Phenomenology', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Philippine literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Philosophy', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Philosophy of religion', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Philosophy of science', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Phoolan Devi', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Picture books', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Poe', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Poetic form', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Poetry', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Polish language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Polish literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Political literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Portuguese language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Portuguese literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Postcolonial exotic', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Postmodernism', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Print culture', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Professional development', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Property rights', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Psychoanalysis', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Publishing', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Pufendorf', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Queer chinese social media.', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Queer cinema', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Queer malaysian sinophonicities', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Queer theory', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Race', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Ramzi Salti', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Reading', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Reading environments', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Religion', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Rhetoric', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Rights', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Roberto Bolaño', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Romance literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Rousseau', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Russell Hoban', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Russian history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Russian language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Russian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Samuel pufendorf', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Sarah waters', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Scalar', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Scandinavian languages', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Scandinavian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Scholarly communication', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Scholarly society', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Second language acquisition', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Serbo-Croatian languages', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Serbo-Croatian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Sexuality', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Sinophone', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Slavic languages', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Slavic literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Social contract', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Social media', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Social reading', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Software', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Southwest', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Southwestern literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Spanish language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Spirituality', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Succession', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Superhero', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Tagalog language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Teaching', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Teaching of language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Teaching of literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Terrorism', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Thai language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Thai literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Theory', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Theory of emotions', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'The sublime', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Third culture kids/adults', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Thomas Pynchon', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Thuggee', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Toni Morrison', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Transgender studies', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Translation', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Ulmer', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'University', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Urbanism', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Urdu language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Victorian literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Vietnamese language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Vietnamese literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'War literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Wikipedia', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Wikis', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'William Caxton', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Women', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'World history', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Yaoi', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Yiddish language', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Yiddish literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Young adult literature', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
$set_term = wp_insert_term( 'Youth culture', 'mla_academic_interests' );
if ( is_wp_error( $set_term ) ) echo var_export( $set_term, true ), "\n";
echo "****************inserts complete*************************\n";
