default:
  base-site-plugins:
    - bbpress
    - bp-attachment-xprofile-field-type
    - bp-rbe-inbound-forum-attachments
    - bp-rbe-new-topic
    - buddypress-group-email-subscription
    - buddypress-messages-spam-blocker
    - bp-reply-by-email
    - buddypress-sitewide-activity-widget
    - classic-widgets
    - elementor
    - elementor-pro
    - gd-bbpress-attachments
    - hc-custom
    - hc-member-profiles
    - hc-notifications
    - invite-anyone
    - mla-allowed-tags
    - siteorigin-panels
    - woosidebars
    - formassembly-web-forms
    - buddypress-docs
    - buddypress-docs-minor-edit
  network-plugins:
    - 15zine-functionality
    - akismet
    - beehive-analytics
    - blog-avatar
    - bp-groupblog
    - bp-group-documents
    - bp-lotsa-feeds
    - bp-mpo-activity-filter
    - bp-block-member
    - buddypress
    - bp-event-organiser
    - buddypress-followers
    - buddypress-restrict-group-creation
    - commons-in-a-box
    - disable-password-reset-extended
    - event-organiser
    - hc-styles
    - humanities-commons
    - mla-academic-interests
    - more-privacy-options
    - redis-cache
    - simplemag-addons
    - wordpress-sparkpost
    - sparkpost-bp-mailer
    - wp-accessibility
    - wp-multi-network
    - cc-client
  allowed-user-plugins:
    - footnotes-made-easy
    - mathml-block
    - pressforward
    - ninja-forms
    - translatepress-multilingual
    - zotpress
    - password-protected
  allowed-user-themes:
    - blockbase
    - dispatch
    - faculty-child
    - faculty
    - foghorn
    - hitchcock
    - hum
    - learningspace
    - maskitto-light
    - origin
    - portfolio-press
    - publish
    - radcliffe
    - responsive
    - reykjavik
    - sparkling
    - suits
    - twentytwenty
    - twentytwentyone
    - twentytwentythree
    - twentytwentytwo
    - vantage-premium
    - vantage
    - wabi
  base-theme: boss-child
  user-theme: twentytwentythree
up.hcommons.org:
  base-site-plugins:
    - -classic-widgets
    - -cron-logger
    - -woosidebars
    - -formassembly-web-forms
mla.hcommons.org:
  base-site-plugins:
    - -buddypress-messages-spam-blocker
    - classic-editor
    - -elementor
    - -elementor-pro
    - -woosidebars
    - -formassembly-web-forms
  network-plugins:
    - -15zine-functionality
    - black-studio-tinymce-widget
    - cbox-auth
    - -buddypress-restrict-group-creation
    - woosidebars
    - -wp-accessibility
    - so-widgets-bundle
  allowed-user-plugins:
    - wordpress-importer
sah.hcommons.org:
  base-site-plugins:
    - -classic-widgets
    - -cron-logger
    - -siteorigin-panels
    - password-protected
    - -woosidebars
    - -formassembly-web-forms
    - essential-addons-for-elementor-lite
  network-plugins:
    - -bp-event-organiser/bp-event-organiser
    - -buddypress-restrict-group-creation
commons.msu.edu:
  base-site-plugins:
    - -classic-widgets
    - -cron-logger
    - essential-addons-for-elementor-lite
    - -siteorigin-panels
    - -woosidebars
    - -formassembly-web-forms
  network-plugins:
    - -bp-event-organiser/bp-event-organiser
    - classic-editor
    - classic-widgets
    - -buddypress-restrict-group-creation
    - redis-cache
arlisna.hcommons.org:
  base-site-plugins:
    - -classic-widgets
    - -cron-logger
    - -siteorigin-panels
    - -woosidebars
    - -formassembly-web-forms
  network-plugins:
    - -bp-event-organiser/bp-event-organiser
    - -buddypress-restrict-group-creation
    - msu-kaltura-oembed
hastac.hcommons.org:
  base-site-plugins:
    - -woosidebars
    - -formassembly-web-forms
    - -classic-widgets
    - -cron-logger
    - -elementor
    - -elementor-pro
    - -siteorigin-panels
    - smart-slider-3
    - feedzy-rss-feeds
  network-plugins:
    - -bp-event-organiser/bp-event-organiser
    - classic-widgets
    - -buddypress-restrict-group-creation
    - -redis-cache
    - -simplemag-addons
    - -15zine-functionality

